name: 'publish'

on:
  push:
    tags:
      - "*"

# This workflow will trigger on each push to the `release` branch to create or update a GitHub release, build your app, and upload the artifacts to the release.
concurrency:
  group: ${{ github.workflow }}-${{  github.ref }}
  cancel-in-progress: true

jobs:
  draft:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Get the tag name
        run : echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: build
        run: |
          rustup target add aarch64-apple-darwin && \
          yarn install && \
          yarn run tauri build -- -v --target aarch64-apple-darwin

        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}

      - name: create draft release
        uses: crabnebula-dev/cloud-release@dev
        id: draft
        with:
          command: release draft ${{ secrets.CN_APP_ID }} ${{ env.TAG_NAME }}
          api-key: ${{ secrets.CN_API_KEY }}

      - name: publish release
        uses: crabnebula-dev/cloud-release@dev
        id: publish
        with: 
          command: release publish ${{ secrets.CN_APP_ID }} ${{ env.TAG_NAME }}
          api-key: ${{ secrets.CN_API_KEY }}